name: Generate TypeScript client from OpenAPI

on:
  schedule:
    - cron: "0 3 * * *" # Runs daily at 3:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-client:
    runs-on: ubuntu-latest

    env:
      OPENAPI_URL: https://api.tryposhub.com/docs/specification.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch all tags

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"

      # - name: Set Yarn to v3 and enable it with Corepack
      #   run: |
      #     corepack enable
      #     corepack prepare yarn@stable --activate

      - name: Install dependencies
        run: yarn install

      - name: Download OpenAPI spec
        run: curl -sSL $OPENAPI_URL -o openapi.json

      - name: Check for existing tag
        id: check
        run: |
          VERSION=$(yq -p=json '.info.version' ./openapi.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          if git tag | grep -q "v$VERSION"; then
            echo "Version v$VERSION already tagged. Skipping generation."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "New version detected: $VERSION"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Generate TypeScript client
        if: steps.check.outputs.changed == 'true'
        run: yarn generate

      - name: Build the distribution
        if: steps.check.outputs.changed == 'true'
        run: yarn build

      - name: Update all package.json versions
        if: steps.check.outputs.changed == 'true'
        run: |
          VERSION=${{ steps.check.outputs.version }}
          echo "Setting version to $VERSION"
          for pkg in $(yq eval '.workspaces[]' package.json | tr -d '"'); do
            for manifest in $(find "$pkg" -name package.json); do
              echo "Updating $manifest"
              yq -p=json -o=json '.version = strenv(VERSION)' "$manifest" > tmp.json && mv tmp.json "$manifest"
            done
          done

      - name: Publish packages
        if: steps.check.outputs.changed == 'true'
        run: yarn workspaces foreach --topological --verbose run publish

      - name: Commit and tag changes
        if: steps.check.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add . || echo "No changes to add"
          git diff --cached --quiet || git commit -m "chore: update client for OpenAPI version ${{ steps.check.outputs.version }}"
          git tag "v${{ steps.check.outputs.version }}"
          git push origin "v${{ steps.check.outputs.version }}"
          git push

      - name: Publish to npm
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
