name: Generate TypeScript client from OpenAPI

on:
  schedule:
    - cron: "0 3 * * *" # Runs daily at 3:00 UTC
  workflow_dispatch: # Manual trigger

permissions:
  contents: write # Required to push changes back to the repository

jobs:
  generate-client:
    runs-on: ubuntu-latest

    env:
      OPENAPI_URL: https://api.tryposhub.com/docs/specification.json
      VERSION_FILE: .openapi-version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Download OpenAPI spec
        run: curl -sSL $OPENAPI_URL -o openapi.json

      - name: Check for version change
        id: check
        run: |
          CURRENT_VERSION=$(yq -p=json '.info.version' ./openapi.json)
          echo "Latest OpenAPI version: $CURRENT_VERSION"
          if [ -f $VERSION_FILE ]; then
            STORED_VERSION=$(cat $VERSION_FILE)
            echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          else
            STORED_VERSION=""
          fi

          echo "Stored version: $STORED_VERSION"

          if [ "$CURRENT_VERSION" != "$STORED_VERSION" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate TypeScript client
        if: steps.check.outputs.changed == 'true'
        run: yarn generate

      - name: Build the distribution
        if: steps.check.outputs.changed == 'true'
        run: yarn build

      - name: Update stored version
        if: steps.check.outputs.changed == 'true'
        run: echo "${{ steps.check.outputs.version }}" > $VERSION_FILE

      - name: Commit and push changes
        if: steps.check.outputs.changed == 'true'
        run: |
          # Run the version patch with parn isntead of npm 
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add . || echo "No changes to add"
          git diff --cached --quiet || git commit -m "chore: update client for OpenAPI version ${{ steps.check.outputs.version }}"
          # Tag the commit
          git tag "v${{ steps.check.outputs.version }}"
          # Push tag first as it will fail if the tag already exists
          git push origin "v${{ steps.check.outputs.version }}"
          git push

      # - name: Bump package version and publish
      #   if: steps.check.outputs.changed == 'true'
      #   run: |
      #     npm version patch --no-git-tag-version
      #     git add package.json package-lock.json
      #     git commit -m "chore: bump version for OpenAPI update"
      #     git tag "v$(node -p "require('./package.json').version")"
      #     git push --follow-tags

      - name: Publish to npm
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
