name: Generate TypeScript client from OpenAPI

on:
  schedule:
    - cron: "0 3 * * *" # Runs daily at 3:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-client:
    runs-on: ubuntu-latest
    env:
      OPENAPI_URL: https://api.tryposhub.com/docs/specification.json
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch all tags

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install

      - name: Download OpenAPI spec
        run: curl -sSL $OPENAPI_URL -o openapi.json

      - name: Check for existing tag
        id: check
        run: |
          VERSION=$(yq -p=json '.info.version' ./openapi.json)
          FIXED_VERSION=$(echo "$VERSION" | sed -E 's/^([0-9]+\.[0-9]+\.[0-9]+)\.([0-9]+)$/\1-\2/')
          echo "version=$FIXED_VERSION" >> $GITHUB_OUTPUT

          if git tag | grep -q "v$VERSION"; then
            echo "Version v$VERSION already tagged. Skipping generation."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "New version detected: $VERSION"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Generate TypeScript client
        if: steps.check.outputs.changed == 'true'
        run: yarn generate

      - name: NX Release
        if: steps.check.outputs.changed == 'true'
        run: yarn nx release ${{ steps.check.outputs.version }} -y
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Build the distribution
      #   if: steps.check.outputs.changed == 'true'
      #   run: yarn build

      # - name: Update all package.json versions
      #   if: steps.check.outputs.changed == 'true'
      #   run: |
      #     VERSION=${{ steps.check.outputs.version }}
      #     echo "Setting version to $VERSION"

      #     for pkg in $(yq e '.workspaces[]' package.json | tr -d '"'); do
      #       for manifest in $(find "$pkg" -name package.json); do
      #         echo "Updating $manifest"
      #         yq e -i ".version = \"$VERSION\"" "$manifest"
      #       done
      #     done

      # - name: Publish packages
      #   if: steps.check.outputs.changed == 'true'
      #   run: yarn workspaces run yarn npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Commit and tag changes
      #   if: steps.check.outputs.changed == 'true'
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git add . || echo "No changes to add"
      #     git diff --cached --quiet || git commit -m "chore: update client for OpenAPI version ${{ steps.check.outputs.version }}"
      #     git tag "v${{ steps.check.outputs.version }}"
      #     git push origin "v${{ steps.check.outputs.version }}"
      #     git push
